
# configuration의 설정 정보를 사용하는 서비스들이 공유하는 설정 정보가 된다

#token:
#  expiration-time: 86400000 # 하루
#  secret: defaultdefaultdefaultdefaultdefaultdefaultdefaultdefaultdefaultdefaultdefaultdefaultdefaultdefaultdefault # 512bit 이상
