services:

  user-service-db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: qwerty
      MARIADB_DATABASE: user_sys
    volumes:
      - "./db/user:/var/lib/mysql"

  order-service-db:
    image: mariadb
    restart: always
    ports:
      - 3307:3306
    environment:
      MARIADB_ROOT_PASSWORD: qwerty
      MARIADB_DATABASE: order_sys
    volumes:
      - "./db/order:/var/lib/mysql"

  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - "./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_ERLANG_COOKIE: myrabbitmq
    ports:
      - 15672:15672
      - 5672:5672

# https://hub.docker.com/r/bitnami/kafka
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
