server:
  port: 8888

spring:
  application:
    name: configuration-service

  cloud:
    config:
      server:
        git:
          uri: https://github.com/devwuu/spring-cloud-study
          default-label: section/configuration
#          http://localhost:8888/configuration/default