server:
  port: 8000

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      default-filters: # filter 중 가장 먼저 실행되고 가장 마지막에 종료된다
        - name: GlobalFilter
          args: # 해당 필터의 Config에 전달할 파라미터
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id : user-service
          uri: lb://USER-SERVICE # lb는 loadbalance. 유레카에서 서비스를 찾아서 라우팅한다, 서로 포트가 다른 인스턴스가 여러개일 경우 어느쪽으로 포워딩 해야할지 모르기 때문에 이름으로 포워딩할 수 있께 한다.
          predicates:
            - Path=/users/**
          filters:
            - CustomFilter
#            - AddRequestHeader=gateway, hello user
#            - AddResponseHeader=gateway, bye user
            - name: LoggerFilter # filter에 옵션을 주기 위해선 name으로 명확하게 해줘야 함. user-service에만 적용될 filter
              args: # 해당 필터의 Config에 전달할 파라미터
                baseMessage: Spring Cloud Gateway Logger Filter
                preLogger: true
                postLogger: true
        - id: catalog-service
          uri: lb://CATALOG-SERVICE
          filters:
            - CustomFilter
#            - AddRequestHeader=gateway, hello catalog
#            - AddResponseHeader=gateway, bye catalog
          predicates:
            - Path=/catalogs/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          filters:
            - CustomFilter
          predicates:
            - Path=/orders/**


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
