server:
  port: 8000

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id : user-service
          uri: http://localhost:8081
          predicates:
            - Path=/users/**
          filters:
            - CustomFilter
#            - AddRequestHeader=gateway, hello user
#            - AddResponseHeader=gateway, bye user
        - id: catalog-service
          uri: http://localhost:8082
          filters:
            - CustomFilter
#            - AddRequestHeader=gateway, hello catalog
#            - AddResponseHeader=gateway, bye catalog
          predicates:
            - Path=/catalogs/**

#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    service-url:
#      defaultZone: http://localhost:8761/eureka
